name: Publish
on: [workflow_dispatch, ]

env:
  MINECRAFT_VERSION: 1.18.2
  JAVA_VERSION: 17
  MOD_VERSION: 0.0.8
  RELEASE_NAME: MC 1.18.2 RELEASE
  VERSION_TYPE: beta
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (GitHub/Modrinth/CurseForge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:

          name: "${{ env.RELEASE_NAME }}"
          version: "${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          version-type: "${{ env.VERSION_TYPE }}"
          changelog-file: CHANGELOG.md
          java: "${{ env.JAVA_VERSION }}"

          # GITHUB
          github-tag: "v${{ env.MOD_VERSION }}+${{ env.MINECRAFT_VERSION }}"
          github-token: "${{ env.GITHUB_TOKEN }}"

          # MODRINTH
          # modrinth-token: "${{ env.MODRINTH_TOKEN }}"
          # modrinth-featured: true

          # CURSEFORGE
          # curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"
